/// generated by didc on WUMBO canister: wkv3f-iiaaa-aaaap-ag73a-cai
///
/// Transaction1 used for get_transaction()
use candid::{CandidType, Nat};
use icrc_ledger_types::icrc1::account::Account;
use serde::Deserialize;

pub type Balance1 = Nat;
pub type TxIndex1 = Nat;
pub type Timestamp1 = u64;

#[derive(CandidType, Deserialize)]
pub struct Burn1 {
    pub from: Account,
    pub memo: Option<serde_bytes::ByteBuf>,
    pub created_at_time: Option<u64>,
    pub amount: Balance1,
}

#[derive(CandidType, Deserialize)]
pub struct Mint1 {
    pub to: Account,
    pub memo: Option<serde_bytes::ByteBuf>,
    pub created_at_time: Option<u64>,
    pub amount: Balance1,
}
#[derive(CandidType, Deserialize)]
pub struct Transfer1 {
    pub to: Account,
    pub fee: Option<Balance1>,
    pub from: Account,
    pub memo: Option<serde_bytes::ByteBuf>,
    pub created_at_time: Option<u64>,
    pub amount: Balance1,
}

#[derive(CandidType, Deserialize)]
pub struct Transaction1 {
    pub burn: Option<Burn1>,
    pub kind: String,
    pub mint: Option<Mint1>,
    pub timestamp: Timestamp1,
    pub index: TxIndex1,
    pub transfer: Option<Transfer1>,
}
