pub mod add_liquidity;
pub mod add_liquidity_amounts;
pub mod add_pool;
pub mod add_token;
pub mod canister;
pub mod chains;
pub mod claims;
pub mod controllers;
pub mod helpers;
pub mod ic;
pub mod kong_backend;
pub mod kong_data;
pub mod pools;
pub mod remove_liquidity;
pub mod remove_liquidity_amounts;
pub mod requests;
pub mod send;
pub mod solana;
pub mod stable_claim;
pub mod stable_kong_settings;
pub mod stable_lp_token;
pub mod stable_memory;
pub mod stable_pool;
pub mod stable_request;
pub mod stable_token;
pub mod stable_transfer;
pub mod stable_tx;
pub mod stable_user;
pub mod swap;
pub mod swap_amounts;
pub mod tokens;
pub mod transfers;
pub mod user;
pub mod user_balances;

pub const APP_NAME: &str = "KongSwap";
pub const APP_VERSION: &str = "v0.0.26";
