mod add_liquidity;
mod add_liquidity_amounts;
mod add_pool;
mod add_token;
mod canister;
mod chains;
mod claims;
mod controllers;
mod helpers;
mod ic;
mod messages;
mod pools;
mod remove_liquidity;
mod remove_liquidity_amounts;
mod requests;
mod send;
mod stable_claim;
mod stable_kong_settings;
mod stable_lp_token;
mod stable_memory;
mod stable_message;
mod stable_pool;
mod stable_request;
mod stable_token;
mod stable_transfer;
mod stable_tx;
mod stable_user;
mod swap;
mod swap_amounts;
mod tokens;
mod transfers;
mod txs;
mod user;
mod user_balances;

pub const APP_NAME: &str = "Kong Swap";
pub const APP_VERSION: &str = "v0.0.13";
