pub mod add_liquidity;
mod add_liquidity_amounts;
pub mod add_pool;
mod add_token;
pub mod chains;
mod claims;
pub mod helpers;
pub mod ic;
pub mod remove_liquidity;
mod remove_liquidity_amounts;
pub mod requests;
pub mod send;
pub mod stable_claim;
pub mod stable_kong_settings;
pub mod stable_lp_token;
pub mod stable_message;
pub mod stable_pool;
pub mod stable_request;
pub mod stable_token;
pub mod stable_transfer;
pub mod stable_tx;
pub mod stable_update;
pub mod stable_user;
pub mod swap;
mod swap_amounts;
pub mod tokens;
pub mod transfers;
pub mod txs;
pub mod user;
mod user_balances;

pub const APP_NAME: &str = "Kong Lib";
pub const APP_VERSION: &str = "v0.0.16";
