mod add_liquidity;
mod add_liquidity_amounts;
mod add_pool;
mod add_token;
mod chains;
mod claims;
pub mod ic;
mod remove_liquidity;
mod remove_liquidity_amounts;
mod send;
pub mod stable_claim;
pub mod stable_lp_token_ledger;
pub mod stable_message;
pub mod stable_pool;
pub mod stable_request;
pub mod stable_token;
pub mod stable_transfer;
pub mod stable_tx;
pub mod stable_user;
mod swap;
mod swap_amounts;
pub mod tokens;
mod transfers;
mod txs;
pub mod user;
mod user_balances;

pub const APP_NAME: &str = "Kong Lib";
pub const APP_VERSION: &str = "v0.0.8";
