mod add_liquidity;
mod add_pool;
mod canister;
mod chains;
mod claims;
mod controllers;
mod helpers;
mod ic;
mod pools;
mod remove_liquidity;
mod requests;
mod send;
mod stable_claim;
mod stable_db_update;
mod stable_kong_settings;
mod stable_lp_token;
mod stable_memory;
mod stable_message;
mod stable_pool;
mod stable_request;
mod stable_token;
mod stable_transfer;
mod stable_tx;
mod stable_user;
mod swap;
mod tokens;
mod transfers;
mod txs;
mod user;

pub const APP_NAME: &str = "Kong Data";
pub const APP_VERSION: &str = "v0.0.15";
