-- AlterTable
ALTER TABLE "pool_stats" ALTER COLUMN "total_tvl" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "total_24h_volume" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "total_24h_lp_fee" SET DATA TYPE DECIMAL(65,0);

-- AlterTable
ALTER TABLE "pools" ALTER COLUMN "balance" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "balance_0" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "lp_fee_0" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "balance_1" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "lp_fee_1" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "rolling_24h_volume" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "rolling_24h_lp_fee" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "lp_token_supply" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "total_volume" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "total_lp_fee" SET DATA TYPE DECIMAL(65,0);

-- AlterTable
ALTER TABLE "tokens" ALTER COLUMN "fee" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "total_supply" SET DATA TYPE DECIMAL(65,0);

-- AlterTable
ALTER TABLE "transactions" ALTER COLUMN "amount0" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "amount1" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "shares" SET DATA TYPE DECIMAL(65,30);
