export const tokenBalancesSelector = {
  ICP: "icpBalance",
  ckBTC: "ckbtcBalance",
  ckETH: "ckethBalance",
  ckUSDC: "ckusdcBalance",
  ckUSDT: "ckusdtBalance",
  DKP: "dkpBalance",
  Bits: "bitsBalance",
  CHAT: "chatBalance",
  nanas: "nanasBalance",
  ND64: "nd64Balance",
  WTN: "wtnBalance", // Include new tokens in balances selector
  YUGE: "yugeBalance",
  nICP: "nicpBalance",
  ALPACALB: "alpacalbBalance",
  PARTY: "partyBalance",
  SNEED: "sneedBalance",
  CLOWN: "clownBalance",
  DAMONIC: "damonicBalance",
  EXE: "exeBalance",
  WUMBO: "wumboBalance",
  MCS: "mcsBalance",
  BOB: "bobBalance",
  BURN: "burnBalance",
  NTN: "ntnBalance",
  DCD: "dcdBalance",
  GLDGov: "gldgovBalance",
  OWL: "owlBalance",
  OGY: "ogyBalance",
  FPL: "fplBalance",
  DITTO: "dittoBalance",
  ICVC: "icvcBalance",
};