const tokenFullNames = {
    ICP: "Internet Computer Protocol",
    ckBTC: "Chain Key Bitcoin",
    ckETH: "Chain Key Ethereum",
    ckUSDC: "Chain Key USD Coin",
    ckUSDT: "Chain Key Tether",
    DKP: "Dragginz",
    Bits: "Bits",
    CHAT: "Open Chat",
    nanas: "Nanas",
    ND64: "ND64",
    WTN: "WaterNeuron",
    YUGE: "Yuge",
    nICP: "nICP",
    ALPACALB: "Alpaca",
    PARTY: "PartyHats",
    SNEED: "Sneed",
    CLOWN: "Clown",
    DAMONIC: "Damonic",
    EXE: "Windoge98",
    WUMBO: "Wumbo",
    MCS: "MCS",
    BOB: "Bob.fun",
    BURN: "Burn",
    NTN: "Neutrinite",
    DCD: "DecideAI",
    GLDGov: "Gold DAO",
    OWL: "Owl",
    OGY: "ORIGYN",
    FPL: "OpenFPL",
    DITTO: "Ditto",
    ICVC: "ICVC",
    GLDT: "Gold Token",
    GHOST: "GHOST",
    CTX: "CatalyzeDAO",
    ELNA: "ELNA",
    DOGMI: "DOGMI",
    EST: "ESTATE",
    PANDA: "ICPanda",
    KINIC: "KINIC",
    DOLR: "YRAL",
    TRAX: "TRAX",
    MOTOKO: "Motoko",
    CKPEPE: "ckPEPE",
    CKSHIB: "ckSHIB",
    DOD: "DOD",
    KONG: "KongSwap",
};

export default tokenFullNames;