name: Rust Backend CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-rust-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Cache Cargo registry + build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key:  ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Download PocketIC server
        uses: dfinity/pocketic@main
        env:
          POCKET_IC_VERSION: 9.0.1

      - name: Install dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.26.0"

      - name: Build kong_backend WASM for testing
        run: bash ./scripts/build_kong_backend.sh local

      - name: Run kong_backend tests
        run: cargo test -p kong_backend